name: hackathon-vale

networks:

  wpp-bot:
    name: wpp-bot
    driver: bridge

services:

  wpp-bot:
    build: .
    container_name: wpp-bot
    env_file: .env
    networks:
      - wpp-bot
    ports:
      - 8000:8000
    develop:
      watch:
        - path: ./go.mod
          action: rebuild
        - path: ./go.sum
          action: rebuild
        - path: ./api
          action: rebuild
        - path: ./cmd
          action: rebuild
